Process_num: 4
data:
  ifos: ["H1", "L1"]
  kind: "${KIND}"
  segment_files:
    H1: ["./segments/O3a/H1-science_segs.segwizard"]
    L1: ["./segments/O3a/L1-science_segs.segwizard"]
  total_interval:
    H1: 
      start: ${TOT_START_INT}
      end: ${TOT_END_INT}
    L1:
      start: ${TOT_START_INT}
      end: ${TOT_END_INT}
  data_cache: "O3_data"
  asd_cache: "/home/app/opt/asds"
  processing:
    window_length: 4
    flow: 30
    fhigh: 1500
    resample: 4096
    crop_length: 1
  background:
    ifos: ["H1", "L1"]
    number_of_samples: ${NUM_SAMPLES}
    sample_interval:
      H1: 
        start: ${START_INT}
        end: ${END_INT}
      L1:
        start: ${START_INT}
        end: ${END_INT}
    segment_files:
      H1: ["./segments/O3a/H1-background_samples-1238172987-23806.segwizard"]
      L1: ["./segments/O3a/L1-background_samples-1238205073-23812.segwizard"]
    start_id: ${START_ID}
    end_id: ${END_ID}
    window_length: 4
    output_file: "/home/app/opt/test_data/bg_data_ids_${START_ID}-${END_ID}.hdf5"
  glitch:
    ifos: ["H1", "L1"]
    sample_interval:
      H1: 
        start: ${START_INT}
        end: ${END_INT}
      L1:
        start: ${START_INT}
        end: ${END_INT}
    segment_files:
      H1: ["./segments/O3a/H1-glitch_samples-1238172987-23806.segwizard"]
      L1: ["./segments/O3a/L1-glitch_samples-1238205073-23812.segwizard"]
    start_id: ${START_ID}
    end_id: ${END_ID}
    glitch_info_files:
      H1: ["./glitch_info/O3a/H1-glitch_info.hdf5"]
      L1: ["./glitch_info/O3a/L1-glitch_info.hdf5"]
    glitch_window_length: 4
    output_file: "/home/app/opt/test_data/glitch_data_ids_${START_ID}-${END_ID}.hdf5"
  injection:
    ifos: ["H1", "L1"]
    number_of_samples: ${NUM_SAMPLES}
    sample_interval:
      H1: 
        start: ${START_INT}
        end: ${END_INT}
      L1:
        start: ${START_INT}
        end: ${END_INT}
    segment_files:
      H1: ["./segments/O3a/H1-injection_samples-1238172987-23806.segwizard"]
      L1: ["./segments/O3a/L1-injection_samples-1238205073-23812.segwizard"]
    start_id: ${START_ID}
    end_id: ${END_ID}
    waveform: "${INJ_WAVEFORM}"
    qm_file: './ccsn_source/Pan_2021/SR.h5'
    sampling_frequency: 16384
    window_length: 4
    target_snr_low: 12
    target_snr_high: 24
    keep_waveform: True
    output_file: "/home/app/opt/test_data/injection_data_type_${INJ_WAVEFORM}_ids_${START_ID}-${END_ID}.hdf5"
s3:
  access_key: XRIYL1052YCQ125N75UM
  secret_key: XES9mLNbxAWKZC1AUcYFlGd7ByyXXSYw5yB3UrwM
  host_base: https://s3-west.nrp-nautilus.io
  bucket: "${BUCKET}"
  common_prefix: O3_data/
  upload_dir: "${UPLOAD_DIR}"
