Training_set_config:

  General_config:
    Event_per_segment: 10
    Event_window_length: 200
    Segment_frequency: 4096
    Segment_length: 8192

  Dataset_dir: "/home/app/test_data"

  Dataset_path: None

  Detectors: ['H1', 'L1']

  Dataset_type: ['glitch', 'noise', 'bbh', 'lfsg', 'hfsg']

  Cutting_type: 'window_cut'

  Cutting_window: {'glitch':[-0.03, 0.03],'noise':[-1,1], 'bbh':[-0.08, 0.01], 'lfsg':[-0.05, 0.05], 'hfsg':[-0.05, 0.05]}

  Cache_path: '/home/app/test_data/training_dataset_cached.json'


Testing_set_config:

  Cutting_type: 'full_scan'

  General_config:
    Event_per_segment: 10
    Event_window_length: 200
    Segment_frequency: 4096
    Segment_length: 8192
  
  Dataset_dir: "/home/app/test_data"

  Dataset_path: None

  Detectors: ['H1', 'L1']

  Dataset_type: ['test']

  Cache_path: '/home/app/test_data/testing_dataset_cached.npy'
  
  

Full_pipeline:
  Training_scheme:
    device: 'cuda:0'
    Output_dir: '/home/app/test_data'


Weakly_Supervised:
  Model_params:
    Class_type: [0,0,1,1,1]
    Model_struct_before_final_layer: [202, 64, 16]

  Training_scheme:
    Early_stopping_applied: True
    Total_epochs: 200
    Batch_size: 384
    Learning_rate: 0.00002
    Least_epochs: 100
    Epochs_interval: 20
    # device: 'cuda:0'
    Ratio_train: 0.8
    Ratio_test: 0.1
    Ratio_validation: 0.2

    Output_dir: None
    Output_file_infix: 'Final_WSC_'
    Output_file_suffix: 'default'


Filtering_Chain:

  Class_to_use: 5
  Output_dir: None
  Output_file_infix: 'Filtering_chain_'
  Output_file_suffix: 'default'

  Class_list: ['glitch', 'noise', 'BBH', 'SGHF', 'SGLF']
  Detectors_list: ['H1', 'L1']

  glitch:
    General:
      Separated_detectors: True

    Model_params_H1:

      Model_struct_half: [101, 10, 20, 10]


    Training_scheme_H1:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.00005
      Least_epochs: 100
      Epochs_interval: 20
      # Cut_ratio: 0.132
      Cut_ratio: 1
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix:

    Model_params_L1:
      Model_struct_half: [101, 10, 10]


    Training_scheme_L1:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.00005
      Least_epochs: 100
      Epochs_interval: 20
      # Cut_ratio: 0.240
      Cut_ratio: 1
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix:

  noise:
    General:
      Separated_detectors: False


    Model_params:
      Model_struct_half: [202, 40, 20]


    Training_scheme:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.001
      Least_epochs: 100
      Epochs_interval: 20
      Cut_ratio: 0.001
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix:

  BBH:
    General:
      Separated_detectors: False

      
    Model_params:
      Model_struct_half: [202, 20, 20]


    Training_scheme:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.00005
      Least_epochs: 100
      Epochs_interval: 20
      Cut_ratio: 0.9
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix:

  SGHF:
    General:
      Separated_detectors: False

      
    Model_params:
      Model_struct_half: [202, 40]


    Training_scheme:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.00005
      Least_epochs: 100
      Epochs_interval: 20
      Cut_ratio: 0.63
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix:


  SGLF:
    General:
      Separated_detectors: False


    Model_params:
      Model_struct_half: [202, 40]


    Training_scheme:
      Early_stopping_applied: False
      Use_cache: False
      Train_wsc: False
      Generate_cache: False
      Total_epochs: 60
      Batch_size: 32
      Learning_rate: 0.00005
      Least_epochs: 100
      Epochs_interval: 20
      Cut_ratio: 0.63
      Ratio_train: 0.8
      Ratio_test: 0.1
      Ratio_validation: 0.2
      Output_dir:
      Output_file_infix:
      Output_file_suffix: