SESSION_CLIENT_CONFIGURATIONS:
  ACCESS_KEY: XRIYL1052YCQ125N75UM
  SECRET_KEY: XES9mLNbxAWKZC1AUcYFlGd7ByyXXSYw5yB3UrwM
  HOST_BASE: https://s3-west.nrp-nautilus.io

SESSION_BUCKET_CONFIGURATIONS:
  BUCKET: cchou
  COMMON_PREFIX: O3_data/