apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-detection-data-bg
  labels:
    k8s-app: gw-detection-data-bg
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gw-detection-data-bg
  template:
    metadata:
      labels:
        k8s-app: gw-detection-data-bg
    spec:
      containers:
        - name: gw-test-bg
          image: dfredin/gwgasf:testinggw
          imagePullPolicy: Always
          resources:
            limits:
              memory: 250Gi
              cpu: 10000m
              ephemeral-storage: 200Gi
            requests:
              memory: 50Gi
              cpu: 5000m
              ephemeral-storage: 50Gi
          env:
            - name: K8S_ENV
              value: "true"
            - name: KIND
              value: "background"
            - name: NUM_SAMPLES
              value: "5000"
            - name: START_ID
              value: "0"
            - name: END_ID
              value: "45"
            - name: INJ_WAVEFORM
              value: "bbh"
            - name: BUCKET
              value: "cchou"
            - name: UPLOAD_DIR
              value: "testing"
            - name: H1_TOT_START_INT
              value: "1238166018"
            - name: H1_TOT_END_INT
              value: "1238856499"
            - name: L1_TOT_START_INT
              value: "1238166018"
            - name: L1_TOT_END_INT
              value: "1238772909"
            - name: H1_START_INT
              value: "1238172987"
            - name: H1_END_INT
              value: "1238196793"
            - name: L1_START_INT
              value: "1238205073"
            - name: L1_END_INT
              value: "1238228885"
            - name: BG_H1_SEGMENT
              value: "1238172987-23806"
            - name: BG_L1_SEGMENT
              value: "1238205073-23812"
            - name: GLITCH_H1_SEGMENT
              value: "1238172987-23806"
            - name: GLITCH_L1_SEGMENT
              value: "1238205073-23812"
            - name: INJ_H1_SEGMENT
              value: "1238172987-23806"
            - name: INJ_L1_SEGMENT
              value: "1238205073-23812"
            - name: ACCESS_KEY_ID
              value: "XRIYL1052YCQ125N75UM"
            - name: SECRET_ACCESS_KEY
              value: "XES9mLNbxAWKZC1AUcYFlGd7ByyXXSYw5yB3UrwM"
            - name: S3_ENDPOINT
              value: "https://s3-west.nrp-nautilus.io"
          # command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && /home/app/opt/run_segments.sh && sleep infinity"]
          # command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && /home/app/opt/run_segments.sh && exec /home/app/micromamba/env/bin/python /home/app/opt/cli.py"]
          # command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && exec /home/app/micromamba/env/bin/python /home/app/opt/cli.py"]
