apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-anomaly-detection-data
  labels:
    k8s-app: gw-anomaly-detection-data
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gw-anomaly-detection-data
  template:
    metadata:
      labels:
        k8s-app: gw-anomaly-detection-data
    spec:
      containers:
        - name: test
          image: dfredin/gwgasf:testing
          resources:
            limits:
              memory: 10Gi
              cpu: 5000m
              ephemeral-storage: 10Gi
            requests:
              memory: 5Gi
              cpu: 1500m
              ephemeral-storage: 5Gi
          env:
            - name: KIND
              value: "background"
            - name: NUM_SAMPLES
              value: "5000"
            - name: START_ID
              value: "0"
            - name: END_ID
              value: "250"
            - name: INJ_WAVEFORM
              value: "bbh"
            - name: BUCKET
              value: "cchou"
            - name: UPLOAD_DIR
              value: "testing"
          # command: ["sh", "-c", "sleep infinity"]
          # command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && sleep infinity"]
          # command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && python cli.py"]
          command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && /home/app/micromamba/env/bin/python /home/app/opt/cli.py"]