apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-anomaly-detection-data
  labels:
    k8s-app: gw-anomaly-detection-data
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gw-anomaly-detection-data
  template:
    metadata:
      labels:
        k8s-app: gw-anomaly-detection-data
    spec:
      containers:
        - name: test
          image: gitlab-registry.nrp-nautilus.io/chiajuichou/gw-anomaly-detection:data
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 50m
          command: ["sh", "-c", "sleep infinity"]
