apiVersion: batch/v1
kind: Job
metadata:
  name: gwgasf-fullpipeline
spec:
  template:
    spec:
      containers:
      - name: gwgasf-fullpipeline
        image: dfredin/gwgasf:testgwdetect
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p test_data/glitch test_data/noise test_data/bbh test_data/lfsg test_data/hfsg test_data/test && \
            poetry run python get_segments.py && \
            poetry run python cli.py --sid 0 --eid 500 --ptype glitch && \
            poetry run python cli.py --sid 500 --eid 1000 --ptype background && \
            poetry run python cli.py --sid 1000 --eid 1500 --ptype injection --itype bbh && \
            poetry run python gw_anomaly_detection/gasf/src/main.py --newgasf --nbbh 500 --nbg 500 --nglitch 500 && \
            poetry run python gw_anomaly_detection/gasf/src/main.py --train --nbbh 500 --nbg 500 --nglitch 500 --epoch 15 --batch 32 && \
            poetry run python gw_anomaly_detection/gasf/src/main.py --nbbh 500 --nbg 500 --nglitch 500
        resources:
          limits:
            memory: 32Gi
            cpu: "6000m"
          requests:
            memory: 32Gi
            cpu: "4000m"
      restartPolicy: Never
  backoffLimit: 5
