apiVersion: batch/v1
kind: Job
metadata:
  name: gwgasf-bgdata
spec:
  template:
    spec:
      containers:
      - name: gwgasf-bgdata
        image: dfredin/gwgasf:gwpipelinetest
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p test_data/noise && \
            poetry run python get_segments.py --samplenum 5000 && \
            poetry run python cli.py --sid 500 --eid 1000 --ptype background
        resources:
          limits:
            memory: 32Gi
            cpu: "6000m"
          requests:
            memory: 16Gi
            cpu: "3000m"
      restartPolicy: Never
  backoffLimit: 5
