apiVersion: batch/v1
kind: Job
metadata:
  name: gwgasf-training
spec:
  template:
    spec:
      containers:
      - name: gwgasf-training
        image: dfredin/gwgasf:gwpipelinetest
        env:
          - name: H1_TOTAL_START
            value: "1238166018"
          - name: H1_TOTAL_END
            value: "1238856499"
          - name: L1_TOTAL_START
            value: "1238166018"
          - name: L1_TOTAL_END
            value: "1238772909"
          - name: H1_KIND_START
            value: "1238172987"
          - name: H1_KIND_END
            value: "1238196793"
          - name: L1_KIND_START
            value: "1238205073"
          - name: L1_KIND_END
            value: "1238228885"
        command: ["conda", "run", "--no-capture-output", "-n", "gwpipelinetest", "bash", "-c"]
        args:
          - |
            mkdir -p test_data/noise
            python gw_anomaly_detection/gasf/src/main.py --train --nbbh 5000 --nbg 5000 --nglitch 5000 --epoch 15 --batch 32
        resources:
          limits:
            memory: 32Gi
            cpu: "6000m"
          requests:
            memory: 16Gi
            cpu: "3000m"
      restartPolicy: Never
  backoffLimit: 5
