apiVersion: batch/v1
kind: Job
metadata:
  name: gwgasf-asds-h1
spec:
  template:
    spec:
      containers:
      - name: gwgasf-asds-h1
        image: dfredin/gwgasf:asdtest
        command: [ "conda", "run", "--no-capture-output", "-n", "gwtesting", "python" ]
        args: [ "run_asd.py", "--ifo", "H1", "--sid", "0", "--eid", "1" ]
        resources:
          limits:
            memory: 32Gi
            cpu: "6000m"
          requests:
            memory: 8Gi
            cpu: "1500m"
      restartPolicy: Never
  backoffLimit: 5
