apiVersion: batch/v1
kind: Job
metadata:
  name: gwgasf-training
spec:
  template:
    spec:
      containers:
      - name: gwgasf-training
        image: dfredin/gwgasf:testgwdetect
        command: ["/bin/sh", "-c"]
        args:
          - |
            poetry run python gw_anomaly_detection/gasf/src/main.py --train --nbbh 500 --nbg 500 --nglitch 500 --epoch 15 --batch 32
        resources:
          limits:
            memory: 32Gi
            cpu: "6000m"
          requests:
            memory: 16Gi
            cpu: "3000m"
      restartPolicy: Never
  backoffLimit: 5
