apiVersion: batch/v1
kind: Job
metadata:
  name: gw-anomaly-detection-data-bg
spec:
  template:
    spec:
      restartPolicy: Never  
      containers:
        - name: test-bg
          image: dfredin/gwgasf:testingdata
          resources:
            limits:
              memory: 15Gi
              cpu: 12750m
              ephemeral-storage: 20Gi
            requests:
              memory: 6Gi
              cpu: 5100m
              ephemeral-storage: 5Gi
          env:
            - name: KIND
              value: "background"
            - name: NUM_SAMPLES
              value: "100000"
            - name: START_ID
              value: "0"
            - name: END_ID
              value: "1000"
            - name: INJ_WAVEFORM
              value: "bbh"
            - name: BUCKET
              value: "cchou"
            - name: UPLOAD_DIR
              value: "testing"
          command: ["sh", "-c", "/home/app/micromamba/env/bin/envsubst < /home/app/opt/data_config.yaml > /home/app/opt/data_config.yaml.tmp && mv /home/app/opt/data_config.yaml.tmp /home/app/opt/data_config.yaml && /home/app/micromamba/env/bin/python /home/app/opt/cli.py"]
