Training_set_config:

  General_config:
    Event_per_segment: 10
    Segment_frequency: 4096
    segment_length: 8192

  Detectors: ['H1', 'L1']

  Dataset_type: ['glitch', 'noise', 'bbh', 'lfsg', 'hfsg']

  Cache_path: '/home/app/test_data/training_dataset_cached'


Testing_set_config:

  Scan_type: 'full_scan'
  

  Smoothing_window: 
  